# This file is auto-generated by hatch-vcs when building/publishing.
# For local development and testing, it may contain placeholder values.

__version__ = "0.0.1.dev0"
version = "0.0.1.dev0"
version_tuple = (0, 0, 1, "dev0")
