# This file is auto-generated by hatch-vcs when building/publishing.
# For local development and testing, it may contain placeholder values.

__version__ = "0.1.9.dev28+gc5f8512.d20250717"
version = "0.1.9.dev28+gc5f8512.d20250717"
version_tuple = (0, 1, 9, "dev28+gc5f8512.d20250717")